export const exampleTrack = {
  album: {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1ZLU77nRzQIaP23mVSYpCQ",
        },
        href: "https://api.spotify.com/v1/artists/1ZLU77nRzQIaP23mVSYpCQ",
        id: "1ZLU77nRzQIaP23mVSYpCQ",
        name: "Hearts2Hearts",
        type: "artist",
        uri: "spotify:artist:1ZLU77nRzQIaP23mVSYpCQ",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "PR",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/2IjkSbisATTpSpVIlFVNkN",
    },
    href: "https://api.spotify.com/v1/albums/2IjkSbisATTpSpVIlFVNkN",
    id: "2IjkSbisATTpSpVIlFVNkN",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273d346fc1102eb417305b5358b",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02d346fc1102eb417305b5358b",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851d346fc1102eb417305b5358b",
        width: 64,
      },
    ],
    is_playable: true,
    name: "The Chase",
    release_date: "2025-02-24",
    release_date_precision: "day",
    total_tracks: 2,
    type: "album",
    uri: "spotify:album:2IjkSbisATTpSpVIlFVNkN",
  },
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/1ZLU77nRzQIaP23mVSYpCQ",
      },
      href: "https://api.spotify.com/v1/artists/1ZLU77nRzQIaP23mVSYpCQ",
      id: "1ZLU77nRzQIaP23mVSYpCQ",
      name: "Hearts2Hearts",
      type: "artist",
      uri: "spotify:artist:1ZLU77nRzQIaP23mVSYpCQ",
    },
  ],
  available_markets: [
    "AR",
    "AU",
    "AT",
    "BE",
    "BO",
    "BR",
    "BG",
    "CA",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DK",
    "DO",
    "DE",
    "EC",
    "EE",
    "SV",
    "FI",
    "FR",
    "GR",
    "GT",
    "HN",
    "HK",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MY",
    "MT",
    "MX",
    "NL",
    "NZ",
    "NI",
    "NO",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "SG",
    "SK",
    "ES",
    "SE",
    "CH",
    "TW",
    "TR",
    "UY",
    "US",
    "GB",
    "AD",
    "LI",
    "MC",
    "ID",
    "JP",
    "TH",
    "VN",
    "RO",
    "IL",
    "ZA",
    "SA",
    "AE",
    "BH",
    "QA",
    "OM",
    "KW",
    "EG",
    "MA",
    "DZ",
    "TN",
    "LB",
    "JO",
    "PS",
    "IN",
    "BY",
    "KZ",
    "MD",
    "UA",
    "AL",
    "BA",
    "HR",
    "ME",
    "MK",
    "RS",
    "SI",
    "KR",
    "BD",
    "PK",
    "LK",
    "GH",
    "KE",
    "NG",
    "TZ",
    "UG",
    "AG",
    "AM",
    "BS",
    "BB",
    "BZ",
    "BT",
    "BW",
    "BF",
    "CV",
    "CW",
    "DM",
    "FJ",
    "GM",
    "GE",
    "GD",
    "GW",
    "GY",
    "HT",
    "JM",
    "KI",
    "LS",
    "LR",
    "MW",
    "MV",
    "ML",
    "MH",
    "FM",
    "NA",
    "NR",
    "NE",
    "PW",
    "PG",
    "PR",
    "WS",
    "SM",
    "ST",
    "SN",
    "SC",
    "SL",
    "SB",
    "KN",
    "LC",
    "VC",
    "SR",
    "TL",
    "TO",
    "TT",
    "TV",
    "VU",
    "AZ",
    "BN",
    "BI",
    "KH",
    "CM",
    "TD",
    "KM",
    "GQ",
    "SZ",
    "GA",
    "GN",
    "KG",
    "LA",
    "MO",
    "MR",
    "MN",
    "NP",
    "RW",
    "TG",
    "UZ",
    "ZW",
    "BJ",
    "MG",
    "MU",
    "MZ",
    "AO",
    "CI",
    "DJ",
    "ZM",
    "CD",
    "CG",
    "IQ",
    "LY",
    "TJ",
    "VE",
    "ET",
    "XK",
  ],
  disc_number: 1,
  duration_ms: 178900,
  explicit: false,
  external_ids: {
    isrc: "KRA302500047",
  },
  external_urls: {
    spotify: "https://open.spotify.com/track/68UrZQUuO3O6eUiD226xHg",
  },
  href: "https://api.spotify.com/v1/tracks/68UrZQUuO3O6eUiD226xHg",
  id: "68UrZQUuO3O6eUiD226xHg",
  is_local: false,
  is_playable: true,
  name: "The Chase",
  popularity: 76,
  preview_url: null,
  track_number: 1,
  type: "track",
  uri: "spotify:track:68UrZQUuO3O6eUiD226xHg",
};

export const exampleTrack2 = {
  "album": {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4tuJ0bMpJh08umKkEXKUI5"
              },
              "href": "https://api.spotify.com/v1/artists/4tuJ0bMpJh08umKkEXKUI5",
              "id": "4tuJ0bMpJh08umKkEXKUI5",
              "name": "Gracie Abrams",
              "type": "artist",
              "uri": "spotify:artist:4tuJ0bMpJh08umKkEXKUI5"
          }
      ],
      "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/0hBRqPYPXhr1RkTDG3n4Mk"
      },
      "href": "https://api.spotify.com/v1/albums/0hBRqPYPXhr1RkTDG3n4Mk",
      "id": "0hBRqPYPXhr1RkTDG3n4Mk",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2731dac3694b3289cd903cb3acf",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e021dac3694b3289cd903cb3acf",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048511dac3694b3289cd903cb3acf",
              "width": 64
          }
      ],
      "is_playable": true,
      "name": "The Secret of Us (Deluxe)",
      "release_date": "2024-10-18",
      "release_date_precision": "day",
      "total_tracks": 20,
      "type": "album",
      "uri": "spotify:album:0hBRqPYPXhr1RkTDG3n4Mk"
  },
  "artists": [
      {
          "external_urls": {
              "spotify": "https://open.spotify.com/artist/4tuJ0bMpJh08umKkEXKUI5"
          },
          "href": "https://api.spotify.com/v1/artists/4tuJ0bMpJh08umKkEXKUI5",
          "id": "4tuJ0bMpJh08umKkEXKUI5",
          "name": "Gracie Abrams",
          "type": "artist",
          "uri": "spotify:artist:4tuJ0bMpJh08umKkEXKUI5"
      }
  ],
  "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
  ],
  "disc_number": 1,
  "duration_ms": 166300,
  "explicit": true,
  "external_ids": {
      "isrc": "USUG12406903"
  },
  "external_urls": {
      "spotify": "https://open.spotify.com/track/7ne4VBA60CxGM75vw0EYad"
  },
  "href": "https://api.spotify.com/v1/tracks/7ne4VBA60CxGM75vw0EYad",
  "id": "7ne4VBA60CxGM75vw0EYad",
  "is_local": false,
  "is_playable": true,
  "name": "That’s So True",
  "popularity": 92,
  "preview_url": null,
  "track_number": 15,
  "type": "track",
  "uri": "spotify:track:7ne4VBA60CxGM75vw0EYad"
}

export const exampleTrack3 = {
  "album": {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2KEqzdPS7M5YwGmiuPTdr5"
              },
              "href": "https://api.spotify.com/v1/artists/2KEqzdPS7M5YwGmiuPTdr5",
              "id": "2KEqzdPS7M5YwGmiuPTdr5",
              "name": "Rina Sawayama",
              "type": "artist",
              "uri": "spotify:artist:2KEqzdPS7M5YwGmiuPTdr5"
          }
      ],
      "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/3stadz88XVpHcXnVYMHc4J"
      },
      "href": "https://api.spotify.com/v1/albums/3stadz88XVpHcXnVYMHc4J",
      "id": "3stadz88XVpHcXnVYMHc4J",
      "images": [
          {
              "height": 640,
              "width": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2735b131d745dafd8666254fe96"
          },
          {
              "height": 300,
              "width": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e025b131d745dafd8666254fe96"
          },
          {
              "height": 64,
              "width": 64,
              "url": "https://i.scdn.co/image/ab67616d000048515b131d745dafd8666254fe96"
          }
      ],
      "is_playable": true,
      "name": "SAWAYAMA",
      "release_date": "2020-04-17",
      "release_date_precision": "day",
      "total_tracks": 13,
      "type": "album",
      "uri": "spotify:album:3stadz88XVpHcXnVYMHc4J"
  },
  "artists": [
      {
          "external_urls": {
              "spotify": "https://open.spotify.com/artist/2KEqzdPS7M5YwGmiuPTdr5"
          },
          "href": "https://api.spotify.com/v1/artists/2KEqzdPS7M5YwGmiuPTdr5",
          "id": "2KEqzdPS7M5YwGmiuPTdr5",
          "name": "Rina Sawayama",
          "type": "artist",
          "uri": "spotify:artist:2KEqzdPS7M5YwGmiuPTdr5"
      }
  ],
  "available_markets": [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "PR",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK"
  ],
  "disc_number": 1,
  "duration_ms": 201060,
  "explicit": false,
  "external_ids": {
      "isrc": "GBK3W1901224"
  },
  "external_urls": {
      "spotify": "https://open.spotify.com/track/1TWNKyNQOBfNUkWWs7FooF"
  },
  "href": "https://api.spotify.com/v1/tracks/1TWNKyNQOBfNUkWWs7FooF",
  "id": "1TWNKyNQOBfNUkWWs7FooF",
  "is_local": false,
  "is_playable": true,
  "name": "XS",
  "popularity": 56,
  "preview_url": null,
  "track_number": 2,
  "type": "track",
  "uri": "spotify:track:1TWNKyNQOBfNUkWWs7FooF"
}

export const exampleSuggestions =  [
    {
        "name": "good 4 u",
        "artist": "Olivia Rodrigo"
    },
    {
        "name": "XS",
        "artist": "Rina Sawayama"
    },
    {
        "name": "Green Light",
        "artist": "Lorde"
    },
    {
        "name": "Chaise Longue",
        "artist": "Wet Leg"
    },
    {
        "name": "So Hot You're Hurting My Feelings",
        "artist": "Caroline Polachek"
    },
    {
        "name": "Don't Kill My Vibe",
        "artist": "Sigrid"
    },
    {
        "name": "Kyoto",
        "artist": "Phoebe Bridgers"
    },
    {
        "name": "Silk Chiffon",
        "artist": "MUNA"
    },
    {
        "name": "Photo ID",
        "artist": "Remi Wolf"
    },
    {
        "name": "Free Yourself",
        "artist": "Jessie Ware"
    }
] 